import { SystemModel, ArchNode, ArchEdge, LayerType, SemanticNodeType, EdgeRelationType } from '@/types'
import { EXAMPLE_SYSTEM } from './example-system'

const NOW = '2026-04-25T09:30:00.000Z'

function n(
  id: string,
  layer: LayerType,
  semanticType: SemanticNodeType,
  label: string,
  x: number,
  y: number,
  properties: Record<string, unknown> = {},
  description = ''
): ArchNode {
  return {
    id,
    type: 'archNode',
    position: { x, y },
    data: {
      semanticType,
      label,
      description,
      properties: { label, ...properties },
      layer,
      crossLayerRefs: [],
      validationErrors: [],
    },
  }
}

function e(id: string, source: string, target: string, relationType: EdgeRelationType, label?: string): ArchEdge {
  return { id, source, target, data: { relationType }, label }
}

export const FINTECH_SYSTEM: SystemModel = {
  id: 'sys-fintech-payments-001',
  name: 'Fintech Payments Hub',
  description: 'Plataforma de pagos y antifraude en tiempo real para canales web y POS',
  owner: 'Enterprise Architecture',
  metadata: {
    version: '1.0.0',
    createdBy: 'ArchStudio mock',
    organization: 'NovaPay',
    domain: 'fintech',
    tags: ['payments', 'event-driven', 'gcp', 'enterprise'],
  },
  createdAt: NOW,
  updatedAt: NOW,
  diagrams: [
    {
      id: 'diag-app-fintech-001',
      systemId: 'sys-fintech-payments-001',
      layer: 'application',
      name: 'Payments Application Architecture',
      description: 'Servicios core de pagos, riesgo y conciliacion',
      metadata: { version: '1.0.0', lastEditedBy: 'Architect Team' },
      reviewStatus: 'draft',
      reviewHistory: [],
      validationResults: [],
      createdAt: NOW,
      updatedAt: NOW,
      nodes: [
        n('grp-app-core', 'application', 'group', 'Core Payments Domain', 340, 70, { width: 540, height: 270 }),
        n('user-merchant', 'application', 'user', 'Merchant Operator', 40, 200),
        n('frontend-portal', 'application', 'frontend_app', 'Merchant Portal', 190, 200, { technology: 'Next.js', owner: 'Digital Channel Team', criticality: 'high', relatedInfraNodeId: 'cr-portal' }),
        n('api-pay', 'application', 'api_service', 'Payments API', 410, 130, { technology: 'Spring Boot', protocol: 'HTTPS', port: 443, owner: 'Core API Team', criticality: 'critical', relatedInfraNodeId: 'cr-api' }),
        n('svc-fraud', 'application', 'backend_service', 'Fraud Scoring Service', 600, 130, { technology: 'Python', runtime: 'Python 3.12', owner: 'Risk Team', criticality: 'critical', relatedInfraNodeId: 'cr-risk' }),
        n('svc-ledger', 'application', 'backend_service', 'Ledger Service', 410, 250, { technology: 'Go', runtime: 'Go 1.23', owner: 'Ledger Team', criticality: 'critical', relatedInfraNodeId: 'cr-ledger' }),
        n('ext-bank', 'application', 'external_system', 'Core Banking Switch', 820, 200, { protocol: 'ISO8583' }),
      ],
      edges: [
        e('fa-1', 'user-merchant', 'frontend-portal', 'calls', 'web'),
        e('fa-2', 'frontend-portal', 'api-pay', 'calls', 'HTTPS'),
        e('fa-3', 'api-pay', 'svc-fraud', 'calls', 'risk score'),
        e('fa-4', 'api-pay', 'svc-ledger', 'writes_to', 'book entry'),
        e('fa-5', 'api-pay', 'ext-bank', 'calls', 'authorize'),
      ],
    },
    {
      id: 'diag-infra-fintech-001',
      systemId: 'sys-fintech-payments-001',
      layer: 'infrastructure',
      name: 'Payments Infrastructure Architecture',
      description: 'Infraestructura GCP multi-servicio para pagos',
      metadata: { version: '1.0.0', lastEditedBy: 'Architect Team' },
      reviewStatus: 'draft',
      reviewHistory: [],
      validationResults: [],
      createdAt: NOW,
      updatedAt: NOW,
      nodes: [
        n('grp-infra-prod', 'infrastructure', 'group', 'Prod Network Boundary', 260, 60, { width: 620, height: 300 }),
        n('lb-global', 'infrastructure', 'gcp_load_balancer', 'Global LB', 70, 180, { gcpProject: 'novapay-prod', protocol: 'HTTPS', port: 443, owner: 'Platform Team' }),
        n('vpc-prod', 'infrastructure', 'gcp_vpc', 'Payments VPC', 300, 90, { gcpProject: 'novapay-prod', region: 'us-central1', owner: 'Network Team' }),
        n('subnet-app', 'infrastructure', 'gcp_subnet', 'Subnet App', 520, 90, { gcpProject: 'novapay-prod', region: 'us-central1', ipAddress: '10.21.0.0/24', owner: 'Network Team' }),
        n('cr-portal', 'infrastructure', 'gcp_cloud_run', 'Cloud Run Portal', 300, 200, { gcpProject: 'novapay-prod', region: 'us-central1', owner: 'Platform Team', criticality: 'high' }),
        n('cr-api', 'infrastructure', 'gcp_cloud_run', 'Cloud Run API', 500, 200, { gcpProject: 'novapay-prod', region: 'us-central1', owner: 'Platform Team', criticality: 'critical' }),
        n('cr-risk', 'infrastructure', 'gcp_cloud_run', 'Cloud Run Risk', 700, 200, { gcpProject: 'novapay-prod', region: 'us-central1', owner: 'Risk Team', criticality: 'critical' }),
        n('cr-ledger', 'infrastructure', 'gcp_cloud_run', 'Cloud Run Ledger', 700, 300, { gcpProject: 'novapay-prod', region: 'us-central1', owner: 'Ledger Team', criticality: 'critical' }),
        n('secret-pay', 'infrastructure', 'secret_manager', 'Secrets Vault', 940, 180, { gcpProject: 'novapay-prod', owner: 'Security Team' }),
      ],
      edges: [
        e('fi-1', 'lb-global', 'cr-portal', 'routes_to'),
        e('fi-2', 'lb-global', 'cr-api', 'routes_to'),
        e('fi-3', 'vpc-prod', 'subnet-app', 'contains'),
        e('fi-4', 'cr-portal', 'subnet-app', 'connects_to'),
        e('fi-5', 'cr-api', 'subnet-app', 'connects_to'),
        e('fi-6', 'cr-risk', 'subnet-app', 'connects_to'),
        e('fi-7', 'cr-ledger', 'subnet-app', 'connects_to'),
        e('fi-8', 'cr-api', 'secret-pay', 'authenticates_with'),
      ],
    },
    {
      id: 'diag-data-fintech-001',
      systemId: 'sys-fintech-payments-001',
      layer: 'data',
      name: 'Payments Data Architecture',
      description: 'Persistencia, cache y streaming de eventos de pagos',
      metadata: { version: '1.0.0', lastEditedBy: 'Architect Team' },
      reviewStatus: 'draft',
      reviewHistory: [],
      validationResults: [],
      createdAt: NOW,
      updatedAt: NOW,
      nodes: [
        n('grp-data-secure', 'data', 'group', 'PCI Data Zone', 190, 80, { width: 590, height: 280 }),
        n('db-ledger', 'data', 'database', 'Ledger DB', 260, 180, { engine: 'PostgreSQL', version: '16', replicationMode: 'multi-region', owner: 'Data Team', criticality: 'critical', relatedAppNodeId: 'svc-ledger' }),
        n('cache-token', 'data', 'cache', 'Token Cache', 500, 180, { engine: 'Redis', version: '7', owner: 'Platform Team', criticality: 'high' }),
        n('queue-settlement', 'data', 'queue', 'Settlement Queue', 740, 180, { engine: 'Kafka', owner: 'Payments Team', criticality: 'high' }),
        n('topic-pay-events', 'data', 'gcp_pubsub', 'Payment Events Topic', 500, 300, { gcpProject: 'novapay-prod', owner: 'Data Platform Team' }),
        n('bucket-audit', 'data', 'gcp_storage', 'Audit Archive', 260, 300, { gcpProject: 'novapay-prod', storageClass: 'NEARLINE', retentionDays: 3650, owner: 'Governance Team' }),
      ],
      edges: [
        e('fd-1', 'db-ledger', 'topic-pay-events', 'publishes_to', 'CDC'),
        e('fd-2', 'cache-token', 'db-ledger', 'reads_from'),
        e('fd-3', 'topic-pay-events', 'queue-settlement', 'subscribes_from'),
        e('fd-4', 'topic-pay-events', 'bucket-audit', 'writes_to', 'batch export'),
      ],
    },
  ],
}

export const HEALTH_SYSTEM: SystemModel = {
  id: 'sys-health-enterprise-001',
  name: 'Healthcare Enterprise Platform',
  description: 'Arquitectura empresarial para historia clinica, interoperabilidad HL7/FHIR y analitica',
  owner: 'Enterprise Architecture Office',
  metadata: {
    version: '1.0.0',
    createdBy: 'ArchStudio mock',
    organization: 'HealthOne',
    domain: 'healthcare',
    tags: ['enterprise-architecture', 'integration', 'security', 'data-governance'],
  },
  createdAt: NOW,
  updatedAt: NOW,
  diagrams: [
    {
      id: 'diag-app-health-001',
      systemId: 'sys-health-enterprise-001',
      layer: 'application',
      name: 'Healthcare Application Landscape',
      description: 'Mapa de aplicaciones y dominios empresariales de salud',
      metadata: { version: '1.0.0', lastEditedBy: 'EA Team' },
      reviewStatus: 'in_review',
      reviewHistory: [],
      validationResults: [],
      createdAt: NOW,
      updatedAt: NOW,
      nodes: [
        n('grp-domain-care', 'application', 'group', 'Care Delivery Domain', 270, 80, { width: 540, height: 260 }),
        n('user-clinician', 'application', 'user', 'Clinician', 60, 170),
        n('portal-care', 'application', 'frontend_app', 'Care Portal', 190, 170, { technology: 'React', owner: 'Digital Health Team', criticality: 'critical', relatedInfraNodeId: 'gke-care' }),
        n('api-fhir', 'application', 'api_service', 'FHIR API Gateway', 380, 140, { technology: 'Java', protocol: 'HTTPS', port: 443, owner: 'Interoperability Team', criticality: 'critical' }),
        n('svc-ehr-adapter', 'application', 'backend_service', 'EHR Adapter Service', 600, 140, { technology: 'Node.js', owner: 'Interoperability Team', relatedInfraNodeId: 'gke-care' }),
        n('svc-analytics', 'application', 'backend_service', 'Population Analytics', 600, 260, { technology: 'Python', owner: 'Data Science Team', relatedInfraNodeId: 'vm-analytics' }),
        n('ext-national-ehr', 'application', 'external_system', 'National EHR Exchange', 860, 170, { protocol: 'FHIR/REST' }),
      ],
      edges: [
        e('ha-1', 'user-clinician', 'portal-care', 'calls'),
        e('ha-2', 'portal-care', 'api-fhir', 'calls', 'HTTPS'),
        e('ha-3', 'api-fhir', 'svc-ehr-adapter', 'routes_to'),
        e('ha-4', 'svc-ehr-adapter', 'ext-national-ehr', 'calls'),
        e('ha-5', 'api-fhir', 'svc-analytics', 'depends_on'),
      ],
    },
    {
      id: 'diag-infra-health-001',
      systemId: 'sys-health-enterprise-001',
      layer: 'infrastructure',
      name: 'Healthcare Infrastructure Topology',
      description: 'Topologia hibrida para cargas criticas de salud',
      metadata: { version: '1.0.0', lastEditedBy: 'EA Team' },
      reviewStatus: 'in_review',
      reviewHistory: [],
      validationResults: [],
      createdAt: NOW,
      updatedAt: NOW,
      nodes: [
        n('grp-network-clinical', 'infrastructure', 'group', 'Clinical Zone', 250, 70, { width: 640, height: 310 }),
        n('net-public', 'infrastructure', 'network', 'Internet / Partner Network', 60, 200),
        n('lb-care', 'infrastructure', 'gcp_load_balancer', 'Clinical LB', 210, 200, { gcpProject: 'healthone-prod', protocol: 'HTTPS', port: 443 }),
        n('vpc-care', 'infrastructure', 'gcp_vpc', 'Health VPC', 350, 110, { gcpProject: 'healthone-prod', region: 'us-east1' }),
        n('subnet-clinical', 'infrastructure', 'gcp_subnet', 'Clinical Subnet', 560, 110, { gcpProject: 'healthone-prod', region: 'us-east1', ipAddress: '10.45.3.0/24' }),
        n('gke-care', 'infrastructure', 'gcp_gke', 'Clinical GKE Cluster', 400, 230, { gcpProject: 'healthone-prod', region: 'us-east1', owner: 'Platform Team' }),
        n('vm-analytics', 'infrastructure', 'gcp_vm', 'Analytics VM', 670, 230, { gcpProject: 'healthone-prod', region: 'us-east1', machineType: 'n2-standard-8', owner: 'Data Team' }),
        n('fw-clinical', 'infrastructure', 'gcp_firewall', 'Clinical Firewall Policy', 920, 190, { gcpProject: 'healthone-prod', protocol: 'TCP', port: 443, owner: 'SecOps' }),
      ],
      edges: [
        e('hi-1', 'net-public', 'lb-care', 'connects_to'),
        e('hi-2', 'lb-care', 'gke-care', 'routes_to'),
        e('hi-3', 'vpc-care', 'subnet-clinical', 'contains'),
        e('hi-4', 'gke-care', 'subnet-clinical', 'connects_to'),
        e('hi-5', 'vm-analytics', 'subnet-clinical', 'connects_to'),
        e('hi-6', 'fw-clinical', 'vpc-care', 'depends_on'),
      ],
    },
    {
      id: 'diag-data-health-001',
      systemId: 'sys-health-enterprise-001',
      layer: 'data',
      name: 'Healthcare Data Architecture',
      description: 'Datos clinicos, mensajeria e historico regulatorio',
      metadata: { version: '1.0.0', lastEditedBy: 'EA Team' },
      reviewStatus: 'in_review',
      reviewHistory: [],
      validationResults: [],
      createdAt: NOW,
      updatedAt: NOW,
      nodes: [
        n('grp-data-governance', 'data', 'group', 'Data Governance Zone', 170, 70, { width: 680, height: 320 }),
        n('db-patient', 'data', 'database', 'Patient Record DB', 240, 180, { engine: 'PostgreSQL', version: '15', replicationMode: 'read-replica', owner: 'Clinical Data Team', criticality: 'critical', relatedAppNodeId: 'svc-ehr-adapter' }),
        n('cache-clinical', 'data', 'cache', 'Clinical Session Cache', 450, 180, { engine: 'Redis', owner: 'Platform Team' }),
        n('queue-hl7', 'data', 'queue', 'HL7 Integration Queue', 660, 180, { engine: 'RabbitMQ', owner: 'Integration Team', criticality: 'high' }),
        n('topic-clinical', 'data', 'gcp_pubsub', 'Clinical Events', 450, 300, { gcpProject: 'healthone-prod', owner: 'Data Platform Team' }),
        n('bucket-regulatory', 'data', 'gcp_storage', 'Regulatory Archive', 240, 300, { gcpProject: 'healthone-prod', storageClass: 'ARCHIVE', retentionDays: 3650, owner: 'Governance Team' }),
      ],
      edges: [
        e('hd-1', 'db-patient', 'topic-clinical', 'publishes_to', 'change events'),
        e('hd-2', 'queue-hl7', 'db-patient', 'writes_to'),
        e('hd-3', 'cache-clinical', 'db-patient', 'reads_from'),
        e('hd-4', 'topic-clinical', 'bucket-regulatory', 'writes_to'),
      ],
    },
  ],
}

export const MOCK_SYSTEMS: SystemModel[] = [
  EXAMPLE_SYSTEM,
  FINTECH_SYSTEM,
  HEALTH_SYSTEM,
]
